### ISSUE TITLE
cms-buildproject-frontend failure

### ISSUE THREAD

**Issue by cooptastic** [WebGateConsultingAG/CloudeeCMS#2]
I have deployed the full install stack in US-EAST-1 and when the code pipeline runs the build stage for the frontend it fails when trying to describe a stack in EU-CENTRAL-1 for some reason (not the region my stack was deployed).
 `[Container] 2020/07/01 13:33:34 Command did not exit successfully aws cloudformation describe-stacks --region eu-central-1 --stack-name ${STACKNAME} > ./frontend/stackinfo.json exit status 255`

I have checked the environment variables and region is set to us-east-1.

**Comment by ThisIsWebGoat** [comment]
Hi and thank you very much for reporting this!
Will be fixed asap to use the proper region in the buildspec file.

greetings from region eu-central-1 :)

**Comment by ThisIsWebGoat** [comment]
Ok, fixed and tested in us-east-1. If your codepipeline is still intact, trigger a "release change" and it should pick up the updated codebase. Thanks again for reporting this and hope you enjoy CloudeeCMS!
